### PR TITLE
Moved contribution information to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dseevr**
Signed-off-by: Bill Robinson <dseevr@users.noreply.github.com>

### CODE REVIEW

**Comment by dseevr** [comment]
I have no idea how anything is done aside from copying the API doc from contivmodel.  I can add a note for that, but someone else will have to add the details for go doc and anything else that is relevant

**Comment by dseevr** [comment]
Updated with info about updating the API Reference page.  Who can write up instructions for go doc and the other stuff?

**Comment by rhim** [comment]
For godoc, ask Ranjith for instructions - most likely it is just a footnote in the doc saying that goes through the PR process since it is auto-gen from code.

I believe other stuff is just editing the site itself, so can be left out.
- Himanshu
     .:|:.:|:.

On Mar 28, 2017, at 10:35 AM, Bill Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Updated with info about updating the API Reference page. Who can write up instructions for go doc and the other stuff?

**Comment by dseevr** [comment]
The go doc stuff is autogenerated from Github (there's a manual "refresh" button at the bottom of the page) and not even hosted on the Contiv website, so I don't think we need to add anything for that...

Anything else to add here?

**Comment by dseevr** [comment]
Added a note about how GoDoc works and how to manually refresh it, too

**Pull request merged**
