### PR TITLE
Correcting page over flow

### PR DESCRIPTION
**Pull request by shampur**
Signed-off-by: Charan Shampur <cshampur@cisco.com>

### CODE REVIEW

**Comment by shampur** [comment]
https://github.com/contiv/ccn/issues/244

**Comment by vishal-j** [comment]
Fixes the scrolling issue. Doesn't address the `Copyright` misalignment though.

**Comment by yuva29** [comment]
@shampur Are we hiding the scroll bar? but the issue still remains right?

**Comment by shampur** [comment]
Both copyright and page overflow are fixed.

**Pull request merged**
