### PR TITLE
openshift

### PR DESCRIPTION
**Pull request by stacykor**
Updates from Sanjeev and Kiran

screen shot 2017-02-22 at 12 38 02 pm
screen shot 2017-02-22 at 12 38 19 pm

### CODE REVIEW

**Comment by stacykor** [comment]
screen shot 2017-02-22 at 12 38 19 pm

**Comment by stacykor** [comment]
screen shot 2017-02-22 at 12 56 21 pm

**Comment by srampal** [comment]
Minor comments Stacy ... otherwise LGTM

1) "Contiv is happy to announce that Openshift Origin v3 supports ..."
2) Openshiftv3 is Red Hat's container platform solution and includes both open source (Openshift Origin) and commercial (Openshift Enterprise/ Container platform) versions.

**Comment by srampal** [comment]
Also, please state that this feature is in a "beta" release stage at this point and please dd a note that refers to the slack contiv-users  channel as an avenue for potential users to ask questions while it is in this state

**Comment by stacykor** [comment]
Done.

**Pull request merged**
